name: Deploy static content to Pages

on:
  push:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: repo checkout
        uses: actions/checkout@v3

      - name: node installation
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: install
        run: npm ci

      - name: build
        run: npm run build
      
      - name: pages installation
        uses: actions/configure-pages@v2
      
      - name: upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './build'
      
      - name: deploy
        id: deploy
        uses: actions/deploy-pages@v1
